{{- if and ( .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" ) ( .Values.serviceMonitor.enabled ) }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "connector.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "connector.labels" . | nindent 4 }}
  {{- if .Values.serviceMonitor.additionalLabels }}
    {{- toYaml .Values.serviceMonitor.additionalLabels | nindent 4 }}
  {{- end }}
spec:
  endpoints:
    {{- .Values.serviceMonitor.scrapeConfigs | toYaml | nindent 4 }}
  selector:
    matchLabels:
      {{- include "connector.selectorLabels" . | nindent 6 }}
{{- end }}
